### ISSUE TITLE
Make changes to address inconsistencies between ActivityContent package and Spec

### ISSUE THREAD

**Issue by aneyzberg** [LibertyDSNP/activity-content#1]
### Problem
Currently there are inconsistencies between our ActivityContent package and our spec. This needs to be addressed. Inconsistencies are listed below. 

- For ActivityContentLocation - spec says name is required -
 SDK has name optional - so need to resolve - required

- For Profile all data fields are optional - so you can have an empty profile. Confirming that we still want this to be the case. - accurate

- For ActvityContentHash - in spec value is required. In SDK we have dynamic values for key. - go with spec

- In Associated Attachments -
Audio
rename - url -> urls
Audio Link
href -> url

- Video Link
rename hash -> hashes

- In Associated Attachments
AudioLink, VideoLink, ImageLink have a hash value - that states Array of hashes for linked content validation - but example shows an object like this: {algorithm: "string", value: string"}
Should this be an array? 

- What should the ActivityContentHash Type look like. - this should be an array

**We do not need to pluralize things**

**Comment by mehtaishita** [comment]
_For ActivityContentLocation_  already correct
_For Profile all data fields are optional_ already correct
_For ActvityContentHash_
_In Associated Attachments _ - the names are already consistent with hred and url

**Comment by wilwade** [comment]
Closed by #4
